server:
  port: 8080

spring:
  application:
    name: digital-gold-wallet

  datasource:
    url: jdbc:mysql://localhost:3306/digital_gold_wallet
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

logging:
  level:
    org.springframework.security: DEBUG