server:
  port: 8080

spring:
  application:
    name: digital-gold-wallet

  datasource:
    url: jdbc:mysql://localhost:3306/digitalgoldwallet
    username: root
    password: your_actual_mysql_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false

logging:
  level:
    org.springframework.security: DEBUG