server:
  port: 8080

spring:

  application:
    name: digital-gold-wallet

  config:
    import: optional:vault://

  cloud:
    vault:
      uri: http://3.25.125.197:8200

      token: ${VAULT_TOKEN}

      kv:
        enabled: true
        backend: secret
        default-context: digital-gold-wallet

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

logging:
  level:
    org.springframework.vault: DEBUG
    org.springframework.cloud.vault: DEBUG

